CREATE TABLE qmost_tiles (
    vid bigint,
    monyear text,
    file text,
    tile_id integer,
    status integer,
    jd_diff double precision,
    ob_ntile integer,
    ob_first_tile_id integer,
    ra double precision,
    "dec" double precision,
    pos double precision,
    texp real,
    isky integer,
    n_subsurveys integer,
    ntotal_tar_lr integer,
    ntotal_tar_hr integer,
    navail_tar_lr integer,
    navail_tar_hr integer,
    nfib_tar_lr integer,
    nfib_tar_hr integer,
    nfib_empty_lr integer,
    nfib_empty_hr integer,
    fh_avail_lr real,
    fh_sci_lr real,
    fh_empty_lr real,
    fh_overexp_lr real,
    fh_uncompl_lr real,
    fh_extra_lr real,
    fh_avail_hr real,
    fh_sci_hr real,
    fh_empty_hr real,
    fh_overexp_hr real,
    fh_uncompl_hr real,
    fh_extra_hr real,
    weather_factor real
);
