CREATE TABLE :wfdhead (
    subsurvey text,
    snid bigint,
    iauc bigint,
    fake integer,
    ra double precision,
    "dec" double precision,
    pixsize real,
    nxpix integer,
    nypix integer,
    ccdnum integer,
    sntype integer,
    nobs integer,
    ptrobs_min integer,
    ptrobs_max integer,
    mwebv real,
    mwebv_err real,
    redshift_helio real,
    redshift_helio_err real,
    redshift_final real,
    redshift_final_err real,
    vpec real,
    vpec_err real,
    hostgal_nmatch integer,
    hostgal_nmatch2 integer,
    hostgal_objid bigint,
    hostgal_photoz real,
    hostgal_photoz_err real,
    hostgal_specz real,
    hostgal_specz_err real,
    hostgal_ra double precision,
    hostgal_dec double precision,
    hostgal_snsep real,
    hostgal_ddlr real,
    hostgal_confusion real,
    hostgal_logmass real,
    hostgal_logmass_err real,
    hostgal_ssfr real,
    hostgal_ssfr_err real,
    hostgal_mag_u real,
    hostgal_mag_g real,
    hostgal_mag_r real,
    hostgal_mag_i real,
    hostgal_mag_z real,
    hostgal_mag_y real,
    hostgal_magerr_u real,
    hostgal_magerr_g real,
    hostgal_magerr_r real,
    hostgal_magerr_i real,
    hostgal_magerr_z real,
    hostgal_magerr_y real,
    hostgal_sb_fluxcal_u real,
    hostgal_sb_fluxcal_g real,
    hostgal_sb_fluxcal_r real,
    hostgal_sb_fluxcal_i real,
    hostgal_sb_fluxcal_z real,
    hostgal_sb_fluxcal_y real,
    peakmjd real,
    search_type integer,
    sim_model_name text,
    sim_model_index integer,
    sim_type_index integer,
    sim_type_name text,
    sim_template_index integer,
    sim_libid integer,
    sim_ngen_libid integer,
    sim_nobs_undefined integer,
    sim_searcheff_mask integer,
    sim_redshift_helio real,
    sim_redshift_cmb real,
    sim_redshift_host real,
    sim_redshift_flag integer,
    sim_vpec real,
    sim_dlmu real,
    sim_lensdmu real,
    sim_ra double precision,
    sim_dec double precision,
    sim_mwebv real,
    sim_peakmjd real,
    sim_mjd_explode real,
    sim_magsmear_coh real,
    sim_av real,
    sim_rv real,
    sim_peakmag_u real,
    sim_peakmag_g real,
    sim_peakmag_r real,
    sim_peakmag_i real,
    sim_peakmag_z real,
    sim_peakmag_y real,
    sim_exposure_u real,
    sim_exposure_g real,
    sim_exposure_r real,
    sim_exposure_i real,
    sim_exposure_z real,
    sim_exposure_y real,
    sim_galfrac_u real,
    sim_galfrac_g real,
    sim_galfrac_r real,
    sim_galfrac_i real,
    sim_galfrac_z real,
    sim_galfrac_y real,
    sim_subsample_index integer
);

CREATE TABLE :wfdphot (
    snid bigint,
    mjd double precision,
    flt text,
    field text,
    phot_flag integer,
    phot_prob real,
    fluxcal double precision,
    fluxcalerr double precision,
    psf_sig1 real,
    sky_sig double precision,
    zpt double precision,
    sim_magobs double precision
);

CREATE TABLE :ddfhead (
    subsurvey text,
    snid bigint,
    iauc bigint,
    fake integer,
    ra double precision,
    "dec" double precision,
    pixsize real,
    nxpix integer,
    nypix integer,
    ccdnum integer,
    sntype integer,
    nobs integer,
    ptrobs_min integer,
    ptrobs_max integer,
    mwebv real,
    mwebv_err real,
    redshift_helio real,
    redshift_helio_err real,
    redshift_final real,
    redshift_final_err real,
    vpec real,
    vpec_err real,
    hostgal_nmatch integer,
    hostgal_nmatch2 integer,
    hostgal_objid bigint,
    hostgal_photoz real,
    hostgal_photoz_err real,
    hostgal_specz real,
    hostgal_specz_err real,
    hostgal_ra double precision,
    hostgal_dec double precision,
    hostgal_snsep real,
    hostgal_ddlr real,
    hostgal_confusion real,
    hostgal_logmass real,
    hostgal_logmass_err real,
    hostgal_ssfr real,
    hostgal_ssfr_err real,
    hostgal_mag_u real,
    hostgal_mag_g real,
    hostgal_mag_r real,
    hostgal_mag_i real,
    hostgal_mag_z real,
    hostgal_mag_y real,
    hostgal_magerr_u real,
    hostgal_magerr_g real,
    hostgal_magerr_r real,
    hostgal_magerr_i real,
    hostgal_magerr_z real,
    hostgal_magerr_y real,
    hostgal_sb_fluxcal_u real,
    hostgal_sb_fluxcal_g real,
    hostgal_sb_fluxcal_r real,
    hostgal_sb_fluxcal_i real,
    hostgal_sb_fluxcal_z real,
    hostgal_sb_fluxcal_y real,
    peakmjd real,
    search_type integer,
    sim_model_name text,
    sim_model_index integer,
    sim_type_index integer,
    sim_type_name text,
    sim_template_index integer,
    sim_libid integer,
    sim_ngen_libid integer,
    sim_nobs_undefined integer,
    sim_searcheff_mask integer,
    sim_redshift_helio real,
    sim_redshift_cmb real,
    sim_redshift_host real,
    sim_redshift_flag integer,
    sim_vpec real,
    sim_dlmu real,
    sim_lensdmu real,
    sim_ra double precision,
    sim_dec double precision,
    sim_mwebv real,
    sim_peakmjd real,
    sim_mjd_explode real,
    sim_magsmear_coh real,
    sim_av real,
    sim_rv real,
    sim_peakmag_u real,
    sim_peakmag_g real,
    sim_peakmag_r real,
    sim_peakmag_i real,
    sim_peakmag_z real,
    sim_peakmag_y real,
    sim_exposure_u real,
    sim_exposure_g real,
    sim_exposure_r real,
    sim_exposure_i real,
    sim_exposure_z real,
    sim_exposure_y real,
    sim_galfrac_u real,
    sim_galfrac_g real,
    sim_galfrac_r real,
    sim_galfrac_i real,
    sim_galfrac_z real,
    sim_galfrac_y real,
    sim_subsample_index integer
);

CREATE TABLE :ddfphot (
    snid bigint,
    mjd double precision,
    flt text,
    field text,
    phot_flag integer,
    phot_prob real,
    fluxcal double precision,
    fluxcalerr double precision,
    psf_sig1 real,
    sky_sig double precision,
    zpt double precision,
    sim_magobs double precision
);

CREATE TABLE :wfdsummary (
    cid bigint,
    gentype integer,
    sntype integer,
    non1a_index integer,
    genz real,
    galztrue real,
    libid bigint,
    ra double precision,
    "dec" double precision,
    mwebv real,
    mu real,
    peakmjd double precision,
    peakmag_g real,
    peakmag_r real,
    peakmag_i real,
    peakmag_z real,
    snrmag_g real,
    snrmag_r real,
    snrmag_i real,
    snrmag_z real,
    nobs integer,
    trestmin double precision,
    trestmax double precision,
    tgapmax real,
    cutmask integer,
    sim_effmask integer,
    hostmag_g real,
    hostmag_r real,
    hostmag_i real,
    hostmag_z real,
    sbflux_g real,
    sbflux_r real,
    sbflux_i real,
    sbflux_z real,
    galid bigint
);

CREATE TABLE :ddfsummary (
    cid bigint,
    gentype integer,
    sntype integer,
    non1a_index integer,
    genz real,
    galztrue real,
    libid bigint,
    ra double precision,
    "dec" double precision,
    mwebv real,
    mu real,
    peakmjd double precision,
    peakmag_g real,
    peakmag_r real,
    peakmag_i real,
    peakmag_z real,
    snrmag_g real,
    snrmag_r real,
    snrmag_i real,
    snrmag_z real,
    nobs integer,
    trestmin double precision,
    trestmax double precision,
    tgapmax real,
    cutmask integer,
    sim_effmask integer,
    hostmag_g real,
    hostmag_r real,
    hostmag_i real,
    hostmag_z real,
    sbflux_g real,
    sbflux_r real,
    sbflux_i real,
    sbflux_z real,
    galid bigint
);
